"""correcion de la tabla usuarios

Revision ID: ee9773d4e61c
Revises: f5b341571a21
Create Date: 2023-03-16 19:51:13.173469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee9773d4e61c'
down_revision = 'f5b341571a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('ADMIN', 'PERSONA', name='tipousuario'), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=postgresql.ENUM('ADMIN', 'PERSONA', name='tipousuario'),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('ADMIN', 'PERSONA', name='tipousuario'),
               existing_nullable=True)
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
